modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
  modId="livingchest"
  displayName="Living Chest"
  version="1.0.0.0"
  description='''A mod that adds Chester (from Don't Starve) to Minecraft.'''
  displayURL="https://www.curseforge.com/minecraft/mc-mods/livingchest"
  updateJSONURL="https://raw.githubusercontent.com/ayloncarrijo/livingchest/master/update.json"
  logoFile="livingchest.png"
  authors="Syllient"

[[dependencies.livingchest]]
  modId="forge"
  mandatory=true
  versionRange="[36,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.livingchest]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.5,1.17)"
  ordering="NONE"
  side="BOTH"

[[dependencies.livingchest]]
  modId="geckolib3"
  mandatory=true
  versionRange="[3.0.65,)"
  ordering="NONE"
  side="BOTH"
